### ISSUE TITLE
Does not keep scroll when switching between components

### ISSUE THREAD

**Issue by metabacalhau** [mark-hahn/vue-keep-scroll#1]
The scroll position is not maintained when I switch components, here's the example: http://jsfiddle.net/5sH6A/147/
The directive updates the element's attribute with the scroll position, however the `this.vm.attached` event never gets fired.
Very handy tool, thanks for sharing!

**Comment by metabacalhau** [comment]
The following hook `return this.vm.attached = function () {...}` never gets called, so I added the following line `this.vm.$on('hook:attached', this.vm.attached);` and the function started to be invoked.
Also the following query `ref = this.$el.querySelectorAll('[data-vuescrlpos]');` doesn't return any elements, perhaps we don't need to query the children of the current element, so I decided to check the current element's attribute only.
The example that I've given now seems to work http://jsfiddle.net/5sH6A/149/

**Comment by mark-hahn** [comment]
Thank you very much for this help.  Can you please do a pull request?

**Comment by ThomasRalee** [comment]
Has this been resolved? Doesn't seems to be working for me too.

**Comment by metabacalhau** [comment]
@ThomasRalee this should work http://jsfiddle.net/5sH6A/282/

**Comment by metabacalhau** [comment]
Sorry, I closed this issue accidentally.

**Comment by mark-hahn** [comment]
PR from desperate-man now in 0.1.1.
