### ISSUE TITLE
TypeError: Cannot read properties of undefined.

### ISSUE THREAD

**Issue by airliajsmith** [mark-hahn/vue-keep-scroll#5]
Not sure if this is still supported, but worth a try.

I get this error after setup:

`Error in directive keep-scroll bind hook: "TypeError: Cannot read properties of undefined (reading 'addEventListener')"`

**Comment by mark-hahn** [comment]
Sorry, I haven't used atom in several years.  You should definitely switch
to vscode.

**Comment by airliajsmith** [comment]
I will look into that. Thanks for getting back to me. :)
